"""Init

Revision ID: b100c7a30238
Revises: 
Create Date: 2023-07-03 11:47:10.526814

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b100c7a30238'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codename', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codename', name='group_codename')
    )
    op.add_column('students', sa.Column('group_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.drop_column('students', 'group_id')
    op.drop_table('groups')
    # ### end Alembic commands ###
